#!/bin/bash

red='\e[31m'
yellow='\e[33m'
green='\e[32m'
none='\e[0m'
config_file="/usr/local/etc/xray/config.json"

# 检查 jq 工具是否安装
check_jq_installed() {
    if ! type jq &>/dev/null; then
        echo -e "${yellow}正在安装 jq 工具...${none}"
        apt-get update && apt-get install -y jq
    fi
}

# 获取本机公网 IP
get_local_ip() {
    local ip=$(curl -s http://api64.ipify.org)
    if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "$ip"
    else
        echo "无法自动获取公网IP地址，请手动输入。"
        read -p "请输入您的公网IP地址: " manual_ip
        if [[ $manual_ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "$manual_ip"
        else
            echo "输入的IP地址格式不正确，请重新运行脚本并输入有效的公网IP地址。"
            exit 1
        fi
    fi
}

# 显示所有入站配置和 Vmess 链接
show_inbound_configs() {
    local config=$(jq '.' "$config_file")
    echo -e "${green}入站节点配置:${none}"

    local length=$(jq '.inbounds | length' <<< "$config")
    for ((i = 0; i < length; i++)); do
        local port=$(jq -r ".inbounds[$i].port" <<< "$config")
        local id=$(jq -r ".inbounds[$i].settings.clients[0].id" <<< "$config")
        local vmess_link="vmess://$(echo -n "{\"add\":\"$local_ip\",\"aid\":\"0\",\"host\":\"\",\"id\":\"$id\",\"net\":\"ws\",\"path\":\"\",\"port\":\"$port\",\"ps\":\"\",\"tls\":\"\",\"type\":\"none\",\"v\":\"2\"}" | base64 -w 0)"

        echo -e "${yellow}序号: $(($i + 1))${none} - 端口: ${port}, Vmess 链接: ${vmess_link}"
    done
}

# 添加新节点
add_new_nodes() {
    # ... 保持原有逻辑不变 ...
}

# 删除节点
delete_node() {
    read -p "请输入要删除的节点序号: " node_index
    local actual_index=$((node_index - 1))
    if ! [[ $actual_index =~ ^[0-9]+$ ]]; then
        echo -e "${red}错误!${none} 请输入有效的序号。\n"
        return
    fi

    local tag=$(jq -r ".inbounds[$actual_index].tag" "$config_file")
    jq "del(.inbounds[$actual_index]) | del(.routing.rules[] | select(.inboundTag == \"$tag\")) | del(.outbounds[] | select(.tag == \"$tag\"))" "$config_file" > "$config_file.tmp" && mv "$config_file.tmp" "$config_file"
    
    echo -e "${green}已删除序号为 $node_index 的节点。${none}"
}

# 主菜单
main_menu() {
    while true; do
        echo -e "\n${green}菜单:${none}"
        echo "1. 查看所有节点连接信息"
        echo "2. 新增节点配置"
        echo "3. 删除节点"
        echo "4. 退出"
        read -p "请输入选项: " choice

        case $choice in
            1) show_inbound_configs ;;
            2) add_new_nodes ;;
            3) delete_node ;;
            4) break ;;
            *) echo -e "${red}无效的选项，请重新选择。${none}" ;;
        esac
    done
}

check_jq_installed
local_ip=$(get_local_ip)
main_menu
